# Generated by Django 2.0.2 on 2018-03-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=4),
            preserve_default=False,
        ),
    ]
