# Generated by Django 2.0.2 on 2018-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('SC', 'Skin Care'), ('PR', 'Powders'), ('SB', 'Scrubs')], default='SC', max_length=10),
        ),
    ]
